apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "santestspringboot2"
  description: "testing backstage 2"
  annotations:
    github.com/project-slug: sanojat/ backstagetest2
    backstage.io/techdocs-ref: "url:https://github.com/sanojat/-backstagetest2/tree/master/"
spec:
  type: service
  lifecycle: experimental
  owner: "sanojat"
